# Site settings
title: Every Stnank, Not Many Twice
#email: victor.glazer@gmail.com
#description: > # this means to ignore newlines until "baseurl:"
#    Art, Finance, Music and Technology 
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
url: "vglazer.github.io" # the base hostname & protocol for your site
github_username:  vglazer
linkedin_username: victorglazer

# Build settings
markdown: kramdown
highlighter: rouge
plugins: [jekyll-gist]

theme: jekyll-theme-tactile
