# Site settings
title: Reticulating Splines
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
    Musings on culture, tech and finance in the age of snake people
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
url: "vglazer.github.io" # the base hostname & protocol for your site
twitter_username: VictorGlazer
github_username:  vglazer

# Build settings
markdown: kramdown
highlighter: rouge
gems: [jekyll-gist]
