# Site settings
title: Let the goat out
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
    Musings on programming and related matters
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
url: "vglazer.github.io" # the base hostname & protocol for your site
twitter_username: VictorGlazer
github_username:  vglazer

# Build settings
markdown: kramdown
highlighter: pygments
